### PR TITLE
Allow user to define the storage class

### PR DESCRIPTION
**Pull request by awels**
When importing an image from a URL, allow the user to specify
which storage class to save the image to. If the user does not
define the storage class, use the 'default' storage class defined
for the project.

Signed-off-by: Alexander Wels <awels@redhat.com>

### CODE REVIEW

**Comment by awels** [comment]
@aglitke remove the hard coded storage class from image URL path.

**Review by aglitke — APPROVED** [review]

**Comment by aglitke** [comment]
@pkliczewski Can you take a look?  We also want to do the same for v2v per the removal of the kubevirt storage class.

**Comment by pkliczewski** [comment]
@awels In v2v we rely on default flag for specific storageClass. Why user needs to know about this detail? BTW why did you not update ovm definitions as well.

**Comment by awels** [comment]
Because we want the user to be able to specify which storage class they want the image written into. The default might not always be the appropriate target. The OVM definitions use a PVC to point to their image. The PVCs are created against a specific storage class, once we get to the OVM, the storage class is part of the PVC and thus doesn't need to be specified anymore.

So the flow goes, create PVC in specific storage class (local hostPath/Gluster/Ceph/Whatever), the PVC is then bound to a PV in that specific storage class. Then when creating the OVM definition we can reference the PVC without caring which storage class the PVC is on.

**Comment by pkliczewski** [comment]
@awels As far as I understand PVC needs to be created and populated with data for both. In this PR we give a user possibility to define `storageClass`. Interesting is that user can select `storageClass` and choose `OVM` type to be created but `storageClass` in this case is ignored. It is confusing to me and it would be for a user.

**Comment by awels** [comment]
What happens right now for import from URL (without this patch) is the following:

1. User enters information, and submits the request.
2. The ansible script creates a PVC with an annotation that contains the source image URL. The PVC has a hard coded storage class of kubevirt (aka only PV that are of storage class kubevirt) can satisfy the request.
3. The PVC is bound to a PV that satisfies the requested storage class (kubevirt in this case).
4. The CDI controller notices the bound PVC with the annotation containing the source image URL.
5. The CDI controller spawns an importer pod that retrieves and imports the image into the PVC.
6. Either a template or an OVM is created from the remaining information the user provided using the PVC as the disk.

This patch changes step 2 to allow the user to specify the storage class they want the PVC bound to. If they don't specify it, it will use the 'default' storage class. If I read the APB correctly this is what the VMware path does, it doesn't specify a storageClass and thus the default is used (at least I couldn't find where the storageClass is specified for the VMware import case).

Now I agree with you that this is an advanced feature (being able to specify where your PVC is bound) and might confuse a user if they don't know what storage class means. But it is needed in cases of a larger cluster with different types of storage where a VM might need to be on a specific type for performance or other reasons.

**Comment by pkliczewski** [comment]
@awels My point is that this PR is confusing for the user because `storageClass` can be specified for both `ovm` and `template` but it only used in one case not both. In my opinion if we want to have this behavior we need to clarify it to the user.

**Comment by awels** [comment]
The OVM or Template is irrelevant for the storageClass, the storage class is relevant for the PVC which is created in both cases. The flow is. create PVC -> Triggers importer POD -> create (OVM or Template) that points to PVC. Create PVC is the part that can use the storageClass information from the user. So the storageClass input field is relevant for both OVM and Template.

**Comment by pkliczewski** [comment]
> So the storageClass input field is relevant for both OVM and Template.

@awels so why are we updating only one template (j2 file) if you say it is relevant for both.

**Comment by awels** [comment]
@pkliczewski Very good question, thank you for that. In the OVM we can just reference the created PVC. We are changing the template j2 file because it defines the PVC to use when we are creating an OVM out of that template. The actual disk image associated with the template is stored in the PVC created by the request in the APB.
 
Now when we want to create a VM out of the template, the information in the template j2 is referenced to create a new PVC (which is where the storageClass changes come in). That PVC gets annotated with the CloneRequest annotation and uses storageClass that is in the template.

Now that I think about it some more, I think in the work-flow for creating an OVM out of the template we should allow the user to select a different storage class. But that is outside of the scope of this patch.
@aglitke you think it makes sense to allow the user to change storageClass when creating an OVM out of a template? Right now it appears the copy will use the same storageClass

**Comment by aglitke** [comment]
@awels I do think it would make sense to offer this choice to the user but it's not part of this PR.  We should consider doing this in the future but not now.

**Comment by awels** [comment]
Right, I was just thinking out loud about things we should do to make the user experience better.

**Pull request merged**
