### PR TITLE
Remove oc login from import via url flow

### PR DESCRIPTION
**Pull request by aglitke**
Once kubevirt aggregates rbac authorization for its CRDs we will no
longer need to login as a cluster adminstrator to provision virtual
machines.  This allows us to remove the strange user/pass fields from
the form.

Depends on: https://github.com/kubevirt/kubevirt/pull/1105 <MERGED>

Signed-off-by: Adam Litke <alitke@redhat.com>

### CODE REVIEW

**Review by awels — COMMENTED** [review]
Are we sure won't have any other common actions like switching project in the future? Maybe not call it login.yml, but common.yml or something?

**Comment by aglitke** [comment]
@awels If we truly need it we can always add it back.  I don't want to leave around unused code.

**Comment by awels** [comment]
Well we are using the switching project in both provision and deprovision. But its not a big deal.

**Comment by aglitke** [comment]
I tested that the switching project works.  I could create a new project and create a vm there.

**Review by awels — APPROVED** [review]
lgtm

**Pull request merged**
