### PR TITLE
Added version to apb description field

### PR DESCRIPTION
**Pull request by vatsalparekh**
This makes the Version info of the apb visible in the Console

### CODE REVIEW

**Comment by vatsalparekh** [comment]
Fixes #57

**Review by pkliczewski — APPROVED** [review]

**Comment by aglitke** [comment]
Are you planning on adding to this PR?  It seems you just changed it from one static value to another static value.  To do this properly I think we need to templatize the apb.yaml file so that the build can automatically inject the version into apb.yaml.  If we don't do this, then it's guaranteed to become stale at some point and cause confusion.

**Comment by aglitke** [comment]
Please don't merge quite yet...

**Comment by pkliczewski** [comment]
I think that on master we need `master` value. Whenever we tag or branch we need to update this value to specific version. We can templetize for any stable versions for master this PR seems to be OK.

**Comment by aglitke** [comment]
How will we remember to update that?

**Comment by pkliczewski** [comment]
The only thing that come to my mind would be to use tag as version for stable branches.

**Comment by vatsalparekh** [comment]
better thing to do here would be to put `version/tag+git-commit` for better tractability
your thoughts @aglitke @pkliczewski ?

**Comment by pkliczewski** [comment]
@vatsalparekh That should be done for stable branches but master is somewhat special where we could not have `version/tag`. For master we could use only `git-commit`. @aglitke Would this approach work for you?

**Comment by aglitke** [comment]
I think we should use some form of git-describe to patch the version when building the container.  To do this you'd need an apb.yaml.in and a new image build target which creates apb,yaml by inserting the calculated version.  In this way the version would always be calculated correctly. 

/cc @rthallisey for your thoughts as well...

**Comment by vatsalparekh** [comment]
any thoughts on this @aglitke @rthallisey ?

**Comment by pkliczewski** [comment]
@rthallisey @aglitke please review

**Comment by rthallisey** [comment]
+1 from me

**Pull request closed without merging**
